[workspace]
members = ["rm-core", "rm-gui", "gather-mapper"]

resolver = "2"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "thin"
strip = "debuginfo"

[profile.dev.package."*"]
opt-level = 2
